name: free-monad-demo
version: 0.0.0
synopsis: Demo Free Monad
maintainer: Linh Nguyen <tuleism@gmail.com>
license: MIT

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers
  - free
  - mtl

executables:
  hpack:
    main: Main.hs
    source-dirs: src
